server:
  port: 8086
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://ly-mysql:3306/heima?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: myredis
  rabbitmq:
    host: ly-mq
    username: leyou
    password: 123321
    virtual-host: /
eureka:
  client:
    service-url:
      defaultZone: http://ly-registry:10086/eureka
logging:
  level:
    com.leyou: debug
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      insert-strategy: not_null
      update-strategy: not_null
  type-aliases-package: com.leyou.user.entity

ly:
  encoder:
    crypt:
      secret: ${random.uuid} # 随机的密钥，使用uuid
      strength: 6 # 加密强度4~31，决定盐加密时的运算强度，超过10以后加密耗时会显著增加
  auth:
    clientId: user-service
    secret: 1234
    includePathPatterns:
      - '/address/**'
      - /info/me # 拦截 /info/me接口
    excludePathPatterns:
      - '/address/me'
    enable: true
