server:
  port: 8083
spring:
  application:
    name: search-service
  jackson:
    default-property-inclusion: non_null # 查询结果不包含空字段
  rabbitmq:
    host: ly-mq
    username: leyou
    password: 123321
    virtual-host: /
eureka:
  client:
    service-url:
      defaultZone: http://ly-registry:10086/eureka
logging:
  level:
    com.leyou: debug
ly:
  elasticsearch:
    hosts: http://ly-es:9200