server:
  port: 8084
spring:
  application:
    name: page-service
  redis:
    host: myredis    #ly-redis
eureka:
  client:
    service-url:
      defaultZone: http://ly-registry:10086/eureka
canal:
  server: ly-canal:11111
  destination: test
logging:
  level:
    t.j.c.client.client: error
    com.leyou: debug