server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ly-mysql:3306/heima?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123
  jackson:
    default-property-inclusion: non_null # json序列化只返回非空属性
  rabbitmq:
    host: ly-mq
    username: leyou
    password: 123321
    virtual-host: /
    template:
      retry:
        enabled: true  # 开启消息的失败重试
        initial-interval: 10000ms  # 重试周期
        max-interval: 80000ms
        multiplier: 2  # 下次重试的周期的倍数
    publisher-confirms: true # 开启生产者确认机制
eureka:
  client:
    service-url:
      defaultZone: http://ly-registry:10086/eureka
logging:
  level:
    com.leyou: debug


mybatis-plus:
  type-aliases-package: com.leyou.entity.entity # 别名扫描包
  # mapper-locations: classpath*:mappers/*.xml # mapper的xml文件地址
  global-config:
    db-config:
      id-type: auto # id默认为自增长
      update-strategy: NOT_EMPTY # 更新时，只更新非空字段
      insert-strategy: NOT_EMPTY # 新增时，只新增非空字段